version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    env_file:
      - .env

  backend:
    build: .
    ports:
      - "3000:5001"
    env_file:
      - .env
    depends_on:
      - redis
